### ISSUE TITLE
Kindly Show The Implementation

### ISSUE THREAD

**Issue by nakshatra-nahar** [cfeck/imagezero#4]
Kindly Show The Implementation of this project because it is show hard to understand file directory
Anyway The Code and complexity acc. to me is much much good than other
appreciate your hardwork
it would be beneficial if you show us Implementation

**Comment by cfeck** [comment]
Could you please be more specific what you are looking for? Are you looking for documentation how to use this in your own code? Do you want to understand the coding algorithm?

**Comment by nakshatra-nahar** [comment]
sorry for the inconvenience...
Yes I want to use this in my own code 
How Can I Use This

**Comment by cfeck** [comment]
See https://github.com/cfeck/imagezero/issues/5
